### PR TITLE
Upgrade few dependencies and fix test, lint errors

### PR DESCRIPTION
**Pull request by rmkanda**
* Upgrade few vulnerable packages
```
added 1083 packages from 832 contributors and audited 8200 packages in 18.553s
found 708 vulnerabilities (1 low, 7 moderate, 698 high, 2 critical)
```
* Updated few dependencies 
```
Package                          Current  Wanted  Latest  Location
@babel/core                        7.1.6   7.6.2   7.6.2  testcafe-reporter-html
@babel/preset-env                  7.1.6   7.6.2   7.6.2  testcafe-reporter-html
@commitlint/cli                    7.2.1   7.6.1   8.2.0  testcafe-reporter-html
@commitlint/config-conventional    7.1.2   7.6.0   8.2.0  testcafe-reporter-html
cross-env                          5.1.5   5.2.1   6.0.3  testcafe-reporter-html
del                                3.0.0   3.0.0   5.1.0  testcafe-reporter-html
eslint                             5.9.0  5.16.0   6.5.1  testcafe-reporter-html
eslint-config-airbnb-base         13.1.0  13.2.0  14.0.0  testcafe-reporter-html
eslint-plugin-import              2.11.0  2.18.2  2.18.2  testcafe-reporter-html
gulp                               3.9.1   3.9.1   4.0.2  testcafe-reporter-html
gulp-eslint                        5.0.0   5.0.0   6.0.0  testcafe-reporter-html
gulp-mocha                         6.0.0   6.0.0   7.0.2  testcafe-reporter-html
husky                              1.2.0   1.3.1   3.0.8  testcafe-reporter-html
lint-staged                        8.1.0   8.2.1   9.4.2  testcafe-reporter-html
testcafe                          0.20.0  0.20.5   1.5.0  testcafe-reporter-html
```
* Fix test errors
* Fix lint errors

### CODE REVIEW

**Comment by IAmJoffa** [comment]
@rmkanda I was going to make a similar set of changes to this and have reviewed them and they look fine. Does anyone @github.com/picuscreative/testcafe-reporter-html have time to review this or provide feedback on how to get this PR merged in?

**Review by IAmJoffa — APPROVED** [review]
I've had a look at these changes and they look fine. I made a similar set before discovering this PR. Sample Test Run:

> testcafe-reporter-html@1.4.4 test /Users/<user>/Projects/public/testcafe-reporter-html
> cross-env NODE_ENV=test gulp build && cross-env NODE_ENV=test gulp test

[13:03:57] Using gulpfile ~/Projects/public/testcafe-reporter-html/gulpfile.js
[13:03:57] Starting 'build'...
[13:03:57] Starting 'clean'...
[13:03:57] Finished 'clean' after 5.38 ms
[13:03:57] Starting '<anonymous>'...
[13:03:57] Finished '<anonymous>' after 297 ms
[13:03:57] Finished 'build' after 304 ms
[13:03:58] Using gulpfile ~/Projects/public/testcafe-reporter-html/gulpfile.js
[13:03:58] Starting 'test'...


  ✓ Should produce report with colors

  1 passing (24ms)

[13:03:59] Finished 'test' after 624 ms

**Comment by rmkanda** [comment]
Thanks @IAmJoffa 

@davidcunha @timnederhoff @ruirochawork @paazmaya  @BrunoLima18 @ricardoparente @ruirochawork Could you please merge it...

**Comment by timnederhoff** [comment]
If I could I would :smile:

**Comment by timnederhoff** [comment]
@davidcunha @ruirochawork @tayay do you have permissions to merge? please respond.
@PicusCreative it is very cool you have the 'html' name as the best suited name for the html reporter of testcafe, but please make use of it!

**Review by spRite75 — APPROVED** [review]

**Comment by rmkanda** [comment]
Thanks @spRite75 Could you please also merge it.

**Comment by spRite75** [comment]
@rmkanda I'm not a collaborator, I just also would like this merged and don't know how else to raise visibility of this. Sorry!

**Review by timnederhoff — APPROVED** [review]

**Comment by timnederhoff** [comment]
Thanks @ruirochawork for adding me as collaborator +1

**Comment by rmkanda** [comment]
Thanks @timnederhoff @ruirochawork

**Comment by rmkanda** [comment]
@timnederhoff Is it possible to make a new release with the fix?

**Comment by timnederhoff** [comment]
@rmkanda sure, I created a new release in Github (and tagged it 1.4.5). But I don't have a place to publish it since I don't have permission to publish it to npmjs.com under the testcafe-reporter-html package name (@ruirochawork could you maybe publish on npmjs.com? or give me permissions?). meanwhile, I published it temporarily under my name: https://www.npmjs.com/package/@timnederhoff/testcafe-reporter-html

**Comment by rmkanda** [comment]
Thanks @timnederhoff

**Comment by timnederhoff** [comment]
@davidcunha you were the last one to publish the release on npmjs.com, could you do this for v1.4.5 too? or ad me as a maintainer in npmjs.com?

**Comment by davidcunha** [comment]
@timnederhoff I added you in npm!

**Comment by timnederhoff** [comment]
Thanks David,
@rmkanda FYI, I published the 1.4.5 version under `testcafe-reporter-html` name now. the `@timnederhoff/restcafe-reporter-html` will be deprecated

**Comment by rmkanda** [comment]
Thanks @timnederhoff @davidcunha

**Pull request merged**
