### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by r-s-sandbox**
- Update dependencies from package.json (gulp and testcafe)
- Update Gulpfile to fix breaking change
- Update fixture and utils to work with latest testcafe version

There is currently a high severity vulnerability with lodash 4.11.17 (https://github.com/lodash/lodash/issues/4348) that is used by testcafe (v1.3.1). I have opened an issue (https://github.com/DevExpress/testcafe/issues/3995) to keep track.

### CODE REVIEW

**Comment by paazmaya** [comment]
@ruirochawork could this be merged?

**Comment by zsid** [comment]
@ruirochawork @paazmaya, do you know if someone will be able to merge this?

**Comment by jesusvallez** [comment]
@davidcunha pliiiiis

**Comment by timnederhoff** [comment]
@davidcunha @ruirochawork @tayay do you have permissions to merge? please respond.
@PicusCreative it is very cool you have the 'html' name as the best suited name for the html reporter of testcafe, but please make use of it!

**Comment by tayay** [comment]
@timnederhoff i'm not have permissions to merge, sorry.
@davidcunha please!!

**Comment by timnederhoff** [comment]
closed because it was covered in #25

**Pull request closed without merging**
